<div class="space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Communication</p><h1 class="mt-1 text-2xl font-black text-zinc-950">Contact Messages</h1><p class="mt-1 text-sm text-zinc-500">Review public website enquiries and track resolution.</p></div><span class="rounded-full bg-red-100 px-3 py-1.5 text-sm font-bold text-red-700">{{ $newCount }} new</span></div>
    @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
    <section class="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div class="grid gap-3 md:grid-cols-[1fr_220px]"><input wire:model.live.debounce.300ms="search" type="search" placeholder="Search name, email or subject..." class="rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"><select wire:model.live="statusFilter" class="rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"><option value="">All statuses</option><option value="new">New</option><option value="read">Read</option><option value="resolved">Resolved</option></select></div></section>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
        <section class="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div class="divide-y divide-zinc-100">@forelse($messages as $message)<button type="button" wire:click="openMessage({{ $message->id }})" class="block w-full px-5 py-4 text-left hover:bg-zinc-50"><div class="flex items-start justify-between gap-4"><div><div class="flex items-center gap-2"><p class="font-bold text-zinc-900">{{ $message->subject }}</p>@if($message->status === 'new')<span class="rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-bold uppercase text-red-700">New</span>@endif</div><p class="mt-1 text-sm text-zinc-600">{{ $message->name }} · {{ $message->email }}</p><p class="mt-2 text-xs text-zinc-400">{{ $message->created_at?->format('d M Y H:i') }}</p></div><span class="text-xs font-semibold text-zinc-500">{{ ucfirst($message->status) }}</span></div></button>@empty<p class="px-6 py-12 text-center text-sm text-zinc-500">No messages found.</p>@endforelse</div>@if($messages->hasPages())<div class="border-t px-5 py-4">{{ $messages->links() }}</div>@endif</section>
        <aside>@if($selectedMessage)<section class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-3"><div><h2 class="text-lg font-black text-zinc-950">{{ $selectedMessage->subject }}</h2><p class="mt-1 text-sm text-zinc-500">{{ $selectedMessage->name }} · {{ $selectedMessage->email }}</p></div><span class="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-bold">{{ ucfirst($selectedMessage->status) }}</span></div>@if($selectedMessage->phone)<p class="mt-4 text-sm"><strong>Phone:</strong> {{ $selectedMessage->phone }}</p>@endif<p class="mt-5 whitespace-pre-line rounded-xl bg-zinc-50 p-4 text-sm leading-6 text-zinc-700">{{ $selectedMessage->message }}</p><div class="mt-5 text-xs text-zinc-500">Received {{ $selectedMessage->created_at?->format('d M Y H:i') }}@if($selectedMessage->handler) · Handled by {{ $selectedMessage->handler->name }}@endif</div>@if($selectedMessage->status !== 'resolved')<button type="button" wire:click="resolve({{ $selectedMessage->id }})" class="mt-5 w-full rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">Mark Resolved</button>@endif</section>@else<div class="rounded-2xl border border-dashed border-zinc-300 bg-white p-10 text-center text-sm text-zinc-500">Select a message to read it.</div>@endif</aside>
    </div>
</div>
