@extends('layouts.public')
@section('title', 'Contact | '.($settings->site_name ?? config('app.name')))
@section('description', 'Contact the official website administration.')
@section('content')
<section class="mx-auto max-w-5xl px-4 py-14 sm:px-6 lg:px-8">
    <div class="grid gap-8 lg:grid-cols-[1fr_1.4fr]">
        <div><p class="text-xs font-bold uppercase tracking-[0.18em]" style="color:var(--site-primary)">Contact</p><h1 class="mt-2 text-3xl font-black text-zinc-950">Get in touch</h1><p class="mt-3 text-sm leading-6 text-zinc-600">Use this form for general website enquiries. Do not submit classified, restricted or operational information.</p><div class="mt-6 space-y-3 text-sm text-zinc-600">@if($settings->address)<p><strong>Address:</strong><br>{{ $settings->address }}</p>@endif @if($settings->phone_primary)<p><strong>Phone:</strong> {{ $settings->phone_primary }}</p>@endif @if($settings->email)<p><strong>Email:</strong> {{ $settings->email }}</p>@endif</div></div>
        <div class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">@if(session('status'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif @if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif<form method="POST" action="{{ route('contact.store') }}" class="space-y-4">@csrf<input type="text" name="website" value="" class="hidden" tabindex="-1" autocomplete="off"><div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1.5 block text-sm font-semibold">Name</label><input name="name" value="{{ old('name') }}" required maxlength="150" class="w-full rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1.5 block text-sm font-semibold">Email</label><input name="email" type="email" value="{{ old('email') }}" required maxlength="255" class="w-full rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"></div></div><div><label class="mb-1.5 block text-sm font-semibold">Phone</label><input name="phone" value="{{ old('phone') }}" maxlength="50" class="w-full rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1.5 block text-sm font-semibold">Subject</label><input name="subject" value="{{ old('subject') }}" required maxlength="200" class="w-full rounded-xl border border-zinc-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1.5 block text-sm font-semibold">Message</label><textarea name="message" required maxlength="10000" rows="7" class="w-full rounded-xl border border-zinc-300 px-3 py-2.5 text-sm">{{ old('message') }}</textarea></div><button type="submit" class="rounded-xl px-5 py-3 text-sm font-bold text-white" style="background:var(--site-primary)">Send Message</button></form></div>
    </div>
</section>
@endsection
